development: &defaults
  adapter:  postgresql
  host:     localhost
  database: zaypaydemo_dev
  username: postgres
  password: postgres
  pool:     5
  timeout:  5000

test:
  <<: *defaults
  database: zaypaydemo<%= ENV['TEST_ENV_NUMBER'] %>